In [15]:
import requests

coins = ['bnb-binance-coin', 'btc-bitcoin', 'vrsc-verus-coin', 'lunc-terra-classic', 'ada-cardano']
raw_data = []

for coin_id in coins:
    url = f"https://api.coinpaprika.com/v1/tickers/{coin_id}?quotes=USD"
    response = requests.get(url)
    raw_data.append(response.json())

print(raw_data)

[{'id': 'bnb-binance-coin', 'name': 'BNB', 'symbol': 'BNB', 'rank': 4, 'total_supply': 139184442, 'max_supply': 200000000, 'beta_value': 1.0012, 'first_data_at': '2017-07-25T00:00:00Z', 'last_updated': '2026-05-07T13:54:12Z', 'quotes': {'USD': {'price': 647.3036086241138, 'volume_24h': 893676833.4972539, 'volume_24h_change_24h': -47.189998626708984, 'market_cap': 90094591570, 'market_cap_change_24h': -0.25999999046325684, 'percent_change_15m': -0.07999999821186066, 'percent_change_30m': -0.36000001430511475, 'percent_change_1h': -0.47999998927116394, 'percent_change_6h': -0.7599999904632568, 'percent_change_12h': 0.46000000834465027, 'percent_change_24h': -0.25999999046325684, 'percent_change_7d': 5.119999885559082, 'percent_change_30d': 0, 'percent_change_1y': 0, 'ath_price': 1370.9838437844724, 'ath_date': '2025-10-13T09:00:44Z', 'percent_from_price_ath': -52.74}}}, {'id': 'btc-bitcoin', 'name': 'Bitcoin', 'symbol': 'BTC', 'rank': 1, 'total_supply': 20025984, 'max_supply': 21000000, 'beta_value': 0.935084, 'first_data_at': '2010-07-17T00:00:00Z', 'last_updated': '2026-05-07T13:51:14Z', 'quotes': {'USD': {'price': 80357.47015439365, 'volume_24h': 27026717437.87536, 'volume_24h_change_24h': -23.850000381469727, 'market_cap': 1609237170519, 'market_cap_change_24h': -1.7300000190734863, 'percent_change_15m': -0.41999998688697815, 'percent_change_30m': -0.8799999952316284, 'percent_change_1h': -0.9599999785423279, 'percent_change_6h': -1.4600000381469727, 'percent_change_12h': -0.9399999976158142, 'percent_change_24h': -1.7300000190734863, 'percent_change_7d': 5.230000019073486, 'percent_change_30d': 0, 'percent_change_1y': 0, 'ath_price': 126173.1777846797, 'ath_date': '2025-10-06T19:00:40Z', 'percent_from_price_ath': -36.17}}}, {'id': 'vrsc-verus-coin', 'name': 'Verus', 'symbol': 'VRSC', 'rank': 9487, 'total_supply': 78550407, 'max_supply': 83540184, 'beta_value': 1.01511, 'first_data_at': '2018-11-29T00:00:00Z', 'last_updated': '2026-05-07T13:53:13Z', 'quotes': {'USD': {'price': 0.7700696937321356, 'volume_24h': 40.31561943598062, 'volume_24h_change_24h': -99.91000366210938, 'market_cap': 0, 'market_cap_change_24h': 0, 'percent_change_15m': -0.09000000357627869, 'percent_change_30m': -0.11999999731779099, 'percent_change_1h': -0.6399999856948853, 'percent_change_6h': -4.420000076293945, 'percent_change_12h': -3.950000047683716, 'percent_change_24h': -4.900000095367432, 'percent_change_7d': 0.75, 'percent_change_30d': 0, 'percent_change_1y': 0, 'ath_price': 6.872066286096264, 'ath_date': '2025-02-15T23:50:04Z', 'percent_from_price_ath': -88.79}}}, {'id': 'luna-terra', 'name': 'Terra Classic', 'symbol': 'LUNC', 'rank': 99, 'total_supply': 6518032236162, 'max_supply': 0, 'beta_value': 1.0341, 'first_data_at': '2019-08-07T00:00:00Z', 'last_updated': '2026-05-07T13:53:13Z', 'quotes': {'USD': {'price': 9.436429248564113e-05, 'volume_24h': 113149918.79489565, 'volume_24h_change_24h': -34.939998626708984, 'market_cap': 640675831, 'market_cap_change_24h': -10.470000267028809, 'percent_change_15m': 0.09000000357627869, 'percent_change_30m': -0.23999999463558197, 'percent_change_1h': 1.059999942779541, 'percent_change_6h': -1.8300000429153442, 'percent_change_12h': 6.28000020980835, 'percent_change_24h': -10.470000267028809, 'percent_change_7d': 25.84000015258789, 'percent_change_30d': 0, 'percent_change_1y': 0, 'ath_price': 119.41793899076701, 'ath_date': '2022-04-05T11:45:00Z', 'percent_from_price_ath': -100}}}, {'id': 'ada-cardano', 'name': 'Cardano', 'symbol': 'ADA', 'rank': 14, 'total_supply': 44995037804, 'max_supply': 45000000000, 'beta_value': 1.61321, 'first_data_at': '2017-10-01T00:00:00Z', 'last_updated': '2026-05-07T13:50:14Z', 'quotes': {'USD': {'price': 0.2658535294488946, 'volume_24h': 387272306.5498567, 'volume_24h_change_24h': -36.86000061035156, 'market_cap': 10264630505, 'market_cap_change_24h': -0.25, 'percent_change_15m': -0.5099999904632568, 'percent_change_30m': -1.1200000047683716, 'percent_change_1h': -1.3300000429153442, 'percent_change_6h': -1.0800000429153442, 'percent_change_12h': 0.23000000417232513, 'percent_change_24h': -0.25, 'percent_change_7d': 8, 'percent_change_30d': 0, 'percent_change_1y': 0, 'ath_price': 3.0950278974839334, 'ath_date': '2021-09-02T06:00:00Z', 'percent_from_price_ath': -91.37}}}]

In [17]:
import pandas as pd

df = pd.json_normalize(raw_data)
df

,id,name,symbol,rank,total_supply,max_supply,beta_value,first_data_at,last_updated,quotes.USD.price,...,quotes.USD.percent_change_1h,quotes.USD.percent_change_6h,quotes.USD.percent_change_12h,quotes.USD.percent_change_24h,quotes.USD.percent_change_7d,quotes.USD.percent_change_30d,quotes.USD.percent_change_1y,quotes.USD.ath_price,quotes.USD.ath_date,quotes.USD.percent_from_price_ath
0,bnb-binance-coin,BNB,BNB,4,139184442,200000000,1.001200,2017-07-25T00:00:00Z,2026-05-07T13:54:12Z,647.303609,...,-0.48,-0.76,0.46,-0.26,5.12,0,0,1370.983844,2025-10-13T09:00:44Z,-52.74
1,btc-bitcoin,Bitcoin,BTC,1,20025984,21000000,0.935084,2010-07-17T00:00:00Z,2026-05-07T13:51:14Z,80357.470154,...,-0.96,-1.46,-0.94,-1.73,5.23,0,0,126173.177785,2025-10-06T19:00:40Z,-36.17
2,vrsc-verus-coin,Verus,VRSC,9487,78550407,83540184,1.015110,2018-11-29T00:00:00Z,2026-05-07T13:53:13Z,0.770070,...,-0.64,-4.42,-3.95,-4.90,0.75,0,0,6.872066,2025-02-15T23:50:04Z,-88.79
3,luna-terra,Terra Classic,LUNC,99,6518032236162,0,1.034100,2019-08-07T00:00:00Z,2026-05-07T13:53:13Z,0.000094,...,1.06,-1.83,6.28,-10.47,25.84,0,0,119.417939,2022-04-05T11:45:00Z,-100.00
4,ada-cardano,Cardano,ADA,14,44995037804,45000000000,1.613210,2017-10-01T00:00:00Z,2026-05-07T13:50:14Z,0.265854,...,-1.33,-1.08,0.23,-0.25,8.00,0,0,3.095028,2021-09-02T06:00:00Z,-91.37

In [18]:
df = df[['name','symbol','last_updated','quotes.USD.price','quotes.USD.percent_change_24h']]
df

,name,symbol,last_updated,quotes.USD.price,quotes.USD.percent_change_24h
0,BNB,BNB,2026-05-07T13:54:12Z,647.303609,-0.26
1,Bitcoin,BTC,2026-05-07T13:51:14Z,80357.470154,-1.73
2,Verus,VRSC,2026-05-07T13:53:13Z,0.770070,-4.90
3,Terra Classic,LUNC,2026-05-07T13:53:13Z,0.000094,-10.47
4,Cardano,ADA,2026-05-07T13:50:14Z,0.265854,-0.25

In [19]:
df = df.rename(columns={
    'name':'coin_name', 'symbol':'coin_symbol',
    'quotes.USD.price': 'price',
    'quotes.USD.percent_change_24h': 'percent_change_24h'
        })

df

,coin_name,coin_symbol,last_updated,price,percent_change_24h
0,BNB,BNB,2026-05-07T13:54:12Z,647.303609,-0.26
1,Bitcoin,BTC,2026-05-07T13:51:14Z,80357.470154,-1.73
2,Verus,VRSC,2026-05-07T13:53:13Z,0.770070,-4.90
3,Terra Classic,LUNC,2026-05-07T13:53:13Z,0.000094,-10.47
4,Cardano,ADA,2026-05-07T13:50:14Z,0.265854,-0.25