In [37]:
!pip install massive
from massive import RESTClient

client = RESTClient("lppjfqABG22zKmPuspOyep56wMdB0772")

tickers = []
for t in client.list_tickers(
	type="FUND",
	market="stocks",
	active="true",
	order="asc",
	limit="100",
	sort="ticker",
	):
    tickers.append(t)

print(tickers)

Requirement already satisfied: massive in /home/cliffe/anaconda3/lib/python3.12/site-packages (2.5.0)
Requirement already satisfied: certifi<2027.0.0,>=2022.5.18 in /home/cliffe/anaconda3/lib/python3.12/site-packages (from massive) (2024.8.30)
Requirement already satisfied: urllib3>=1.26.9 in /home/cliffe/anaconda3/lib/python3.12/site-packages (from massive) (2.2.3)
Requirement already satisfied: websockets>=14.0 in /home/cliffe/anaconda3/lib/python3.12/site-packages (from massive) (16.0)

In [38]:
type(tickers)

list

In [39]:
import pandas as pd
df = pd.DataFrame(tickers)
df

,active,cik,composite_figi,currency_name,currency_symbol,base_currency_symbol,base_currency_name,delisted_utc,last_updated_utc,locale,market,name,primary_exchange,share_class_figi,ticker,type,source_feed
0,True,0001503290,BBG0017VSC04,usd,None,None,None,None,2026-04-22T06:09:41.986203257Z,us,stocks,abrdn Income Credit Strategies Fund,XNYS,BBG001TCSLH4,ACP,FUND,None
1,True,0001636289,BBG008HMBD22,usd,None,None,None,None,2026-04-22T06:09:41.986205341Z,us,stocks,Virtus Diversified Income & Convertible Fund,XNYS,BBG008HMBD31,ACV,FUND,None
2,True,0000002230,BBG000BB8MR6,usd,None,None,None,None,2026-04-22T06:09:41.986211783Z,us,stocks,"Adams Diversified Equity Fund, Inc",XNYS,BBG001S5NDV7,ADX,FUND,None
3,True,0000846676,BBG000BGWCV5,usd,None,None,None,None,2026-04-22T06:09:41.986212805Z,us,stocks,"abrdn Emerging Markets ex-China Fund, Inc.",XASE,BBG001S5QCR1,AEF,FUND,None
4,True,0001162027,BBG000DTM676,usd,None,None,None,None,2026-04-22T06:09:41.986215551Z,us,stocks,"Alliance National Municipal Income Fund, Inc.",XNYS,BBG001SK6452,AFB,FUND,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,True,0001163792,BBG000BPYDK3,usd,None,None,None,None,2026-04-22T06:09:41.987822442Z,us,stocks,Western Asset Premier Bond Fund,XNYS,BBG001SB94R5,WEA,FUND,None
337,True,0001254370,BBG000BRVNL9,usd,None,None,None,None,2026-04-22T06:09:41.987829315Z,us,stocks,Western Asset Inflation-Linked Income Fund,XNYS,BBG001SBSMH5,WIA,FUND,None
338,True,0001267902,BBG000BSK789,usd,None,None,None,None,2026-04-22T06:09:41.987830828Z,us,stocks,Western Asset Inflation-Linked Opportunities &...,XNYS,BBG001SBWXC1,WIW,FUND,None
339,True,0001703079,BBG00HMS4SC7,usd,None,None,None,None,2026-04-22T06:09:41.987855465Z,us,stocks,XAI Octagon Floating Rate and Alternative Inco...,XNYS,BBG00HMS4SD6,XFLT,FUND,None
340,True,0000836412,BBG000BXB8X8,usd,None,None,None,None,2026-04-22T06:09:41.987903327Z,us,stocks,Virtus Total Return Fund Inc.,XNYS,BBG001S5XNL5,ZTR,FUND,None

In [40]:
df.count()

active                  341
cik                     341
composite_figi          340
currency_name           341
currency_symbol           0
base_currency_symbol      0
base_currency_name        0
delisted_utc              0
last_updated_utc        341
locale                  341
market                  341
name                    341
primary_exchange        341
share_class_figi        340
ticker                  341
type                    341
source_feed               0
dtype: int64

In [41]:
df.drop(['currency_symbol', 'base_currency_symbol', 'base_currency_name', 'delisted_utc', 'source_feed'], axis=1,inplace=True)
df

,active,cik,composite_figi,currency_name,last_updated_utc,locale,market,name,primary_exchange,share_class_figi,ticker,type
0,True,0001503290,BBG0017VSC04,usd,2026-04-22T06:09:41.986203257Z,us,stocks,abrdn Income Credit Strategies Fund,XNYS,BBG001TCSLH4,ACP,FUND
1,True,0001636289,BBG008HMBD22,usd,2026-04-22T06:09:41.986205341Z,us,stocks,Virtus Diversified Income & Convertible Fund,XNYS,BBG008HMBD31,ACV,FUND
2,True,0000002230,BBG000BB8MR6,usd,2026-04-22T06:09:41.986211783Z,us,stocks,"Adams Diversified Equity Fund, Inc",XNYS,BBG001S5NDV7,ADX,FUND
3,True,0000846676,BBG000BGWCV5,usd,2026-04-22T06:09:41.986212805Z,us,stocks,"abrdn Emerging Markets ex-China Fund, Inc.",XASE,BBG001S5QCR1,AEF,FUND
4,True,0001162027,BBG000DTM676,usd,2026-04-22T06:09:41.986215551Z,us,stocks,"Alliance National Municipal Income Fund, Inc.",XNYS,BBG001SK6452,AFB,FUND
...,...,...,...,...,...,...,...,...,...,...,...,...
336,True,0001163792,BBG000BPYDK3,usd,2026-04-22T06:09:41.987822442Z,us,stocks,Western Asset Premier Bond Fund,XNYS,BBG001SB94R5,WEA,FUND
337,True,0001254370,BBG000BRVNL9,usd,2026-04-22T06:09:41.987829315Z,us,stocks,Western Asset Inflation-Linked Income Fund,XNYS,BBG001SBSMH5,WIA,FUND
338,True,0001267902,BBG000BSK789,usd,2026-04-22T06:09:41.987830828Z,us,stocks,Western Asset Inflation-Linked Opportunities &...,XNYS,BBG001SBWXC1,WIW,FUND
339,True,0001703079,BBG00HMS4SC7,usd,2026-04-22T06:09:41.987855465Z,us,stocks,XAI Octagon Floating Rate and Alternative Inco...,XNYS,BBG00HMS4SD6,XFLT,FUND
340,True,0000836412,BBG000BXB8X8,usd,2026-04-22T06:09:41.987903327Z,us,stocks,Virtus Total Return Fund Inc.,XNYS,BBG001S5XNL5,ZTR,FUND

In [56]:
from massive import RESTClient

client = RESTClient("lppjfqABG22zKmPuspOyep56wMdB0772")

companies = ["AAPL", "GOOG", "TSLA", "AMZN", "NFLX"]
data = []

for ticker in companies:
    request = client.get_daily_open_close_agg(
        ticker,
        "2025-04-22",
        adjusted="true",
    )
    data.append(request)
data

[DailyOpenCloseAgg(after_hours=205, close=199.74, from_='2025-04-22', high=201.59, low=195.97, open=196.12, pre_market=193.79, status='OK', symbol='AAPL', volume=52976371.0, otc=None),
 DailyOpenCloseAgg(after_hours=157.05, close=153.9, from_='2025-04-22', high=154.61, low=150.87, open=151.07, pre_market=151.36, status='OK', symbol='GOOG', volume=15910327.0, otc=None),
 DailyOpenCloseAgg(after_hours=250.8, close=237.97, from_='2025-04-22', high=242.79, low=229.8501, open=230.96, pre_market=230.24, status='OK', symbol='TSLA', volume=120858452.0, otc=None),
 DailyOpenCloseAgg(after_hours=179.82, close=173.18, from_='2025-04-22', high=176.78, low=169.35, open=169.845, pre_market=169.29, status='OK', symbol='AMZN', volume=56607202.0, otc=None),
 DailyOpenCloseAgg(after_hours=105.343, close=104.034, from_='2025-04-22', high=106.497, low=100.452, open=100.53, pre_market=99.3, status='OK', symbol='NFLX', volume=93688730.0, otc=None)]

In [57]:
type(data)

list

In [60]:
df = pd.DataFrame(data)
df_json = json.loads(df.to_json(orient="records"))
df_json

[{'after_hours': 205.0,
  'close': 199.74,
  'from_': '2025-04-22',
  'high': 201.59,
  'low': 195.97,
  'open': 196.12,
  'pre_market': 193.79,
  'status': 'OK',
  'symbol': 'AAPL',
  'volume': 52976371.0,
  'otc': None},
 {'after_hours': 157.05,
  'close': 153.9,
  'from_': '2025-04-22',
  'high': 154.61,
  'low': 150.87,
  'open': 151.07,
  'pre_market': 151.36,
  'status': 'OK',
  'symbol': 'GOOG',
  'volume': 15910327.0,
  'otc': None},
 {'after_hours': 250.8,
  'close': 237.97,
  'from_': '2025-04-22',
  'high': 242.79,
  'low': 229.8501,
  'open': 230.96,
  'pre_market': 230.24,
  'status': 'OK',
  'symbol': 'TSLA',
  'volume': 120858452.0,
  'otc': None},
 {'after_hours': 179.82,
  'close': 173.18,
  'from_': '2025-04-22',
  'high': 176.78,
  'low': 169.35,
  'open': 169.845,
  'pre_market': 169.29,
  'status': 'OK',
  'symbol': 'AMZN',
  'volume': 56607202.0,
  'otc': None},
 {'after_hours': 105.343,
  'close': 104.034,
  'from_': '2025-04-22',
  'high': 106.497,
  'low': 100.452,
  'open': 100.53,
  'pre_market': 99.3,
  'status': 'OK',
  'symbol': 'NFLX',
  'volume': 93688730.0,
  'otc': None}]

In [61]:
df_transform = pd.DataFrame(df_json)
df_transform

,after_hours,close,from_,high,low,open,pre_market,status,symbol,volume,otc
0,205.000,199.740,2025-04-22,201.590,195.9700,196.120,193.79,OK,AAPL,52976371.0,None
1,157.050,153.900,2025-04-22,154.610,150.8700,151.070,151.36,OK,GOOG,15910327.0,None
2,250.800,237.970,2025-04-22,242.790,229.8501,230.960,230.24,OK,TSLA,120858452.0,None
3,179.820,173.180,2025-04-22,176.780,169.3500,169.845,169.29,OK,AMZN,56607202.0,None
4,105.343,104.034,2025-04-22,106.497,100.4520,100.530,99.30,OK,NFLX,93688730.0,None

In [63]:
df_transform = df_transform.rename(columns={"from_": "date"})
df_transform = df_transform.drop(["otc"], axis=1)
df_transform["price change"] = df_transform["close"] - df_transform["open"]
df_transform

,after_hours,close,date,high,low,open,pre_market,status,symbol,volume,price change
0,205.000,199.740,2025-04-22,201.590,195.9700,196.120,193.79,OK,AAPL,52976371.0,3.620
1,157.050,153.900,2025-04-22,154.610,150.8700,151.070,151.36,OK,GOOG,15910327.0,2.830
2,250.800,237.970,2025-04-22,242.790,229.8501,230.960,230.24,OK,TSLA,120858452.0,7.010
3,179.820,173.180,2025-04-22,176.780,169.3500,169.845,169.29,OK,AMZN,56607202.0,3.335
4,105.343,104.034,2025-04-22,106.497,100.4520,100.530,99.30,OK,NFLX,93688730.0,3.504